### ISSUE TITLE
Build guide request

### ISSUE THREAD

**Issue by machinehistories** [shmoergh/hog#1]
This is a terrific looking device and I'd be interested to try and build one. I see the guide on the synth features but do you have a build guide. Is there one already available and if not is there one in the works. Keep up the good work. Thanks

**Comment by peterzimon** [comment]
@machinehistories Thank you! I'm working on one, will ping you when it's available 😎

**Comment by machinehistories** [comment]
thanks appreciate it

**Comment by peterzimon** [comment]
@machinehistories I've added BOMs and production files to all boards.

Also I've written a build guide here:

[https://www.shmoergh.com/hog-build-guide/](https://www.shmoergh.com/hog-build-guide/)

Hope it's useful ✌️

**Comment by machinehistories** [comment]
thanks that's terrific
