### ISSUE TITLE
Research and replace non-precision trimmers to SMD ones

### ISSUE THREAD

**Issue by peterzimon** [shmoergh/hog#12]
- [x] Research parts
- [ ] Replace 'em

**Comment by shmoergh** [comment]
JLCPCB parts
100kΩ — C719186
10kΩ — C911365
50kΩ — C145161

**Comment by shmoergh** [comment]
Changed plan: the available SMD components can only be set from the top (vertically) so the UI board would cover the trimpots making it non-accessible.
