### ISSUE TITLE
Create streamlined only Core board

### ISSUE THREAD

**Issue by shmoergh** [shmoergh/hog#27]
There are a couple of circuit parts on the Core board that allow to choose different options to build:

- Builders can choose whether to use NTC or PTS100 based thermal compensation
- It has +/-5V outputs without using it on the Core board itself
- It has a power terminal that's not used
- There are both SMD and THT J111 footprints in the VCO

There should be an opinionated board which gets rid of all this and streamlines for a single, tested solution. This can only happen if all common fixes are applied already otherwise both boards have to be maintained.

**Comment by peterzimon** [comment]
Closed with https://github.com/shmoergh/hog/commit/a9f9715e1053f44825b6762ae9e018dc59ed68b0
